# Messages sent to player on flight enable and disable.
Message-sent-to-player-on-flight-enable: "(§l§e!§r)§l§eFlight has been enabled!"
Message-sent-to-player-on-flight-disable: "(§l§e!§r)§l§eFlight has been disabled!"

# Message sent to player when /feed is ran

message-sent-to-player-when-fed: "(§l!§r)§l§3You have been saturated!"

# Message sent to player when /heal is ran

message-sent-toplayer-when-healed: "(§l!§r)§l§aHealth restored!"

# Set this to true if you do not want players to be able to fly and pvp simultaneously. Flight is only disabled if the player flying hits the other player, not the other way around.

flight-disabled-on-hit: true

# Message sent to player if they attempt to fly during combat, will only appear if flight-disabled-on-hit is set to true.

no-flight-during-combat-message: "(§l§e!§r)§cFlying during combat is not permitted!"